#pragma once

#include "Adafruit_TinyUSB.h"

const uint8_t hid_asciimap[][3] = {
    {' ', 0, HID_KEY_SPACE},
    {'!', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_1},
    {'"', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_APOSTROPHE},
    {'#', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_3},
    {'$', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_4},
    {'%', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_5},
    {'&', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_7},
    {'\'', 0, HID_KEY_APOSTROPHE},
    {'(', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_9},
    {')', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_0},
    {'*', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_8},
    {'+', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_EQUAL},
    {',', 0, HID_KEY_COMMA},
    {'-', 0, HID_KEY_MINUS},
    {'.', 0, HID_KEY_PERIOD},
    {'/', 0, HID_KEY_SLASH},
    {':', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_SEMICOLON},
    {';', 0, HID_KEY_SEMICOLON},
    {'<', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_COMMA},
    {'=', 0, HID_KEY_EQUAL},
    {'>', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_PERIOD},
    {'?', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_SLASH},
    {'@', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_2},
    {'[', 0, HID_KEY_BRACKET_LEFT},
    {'\\', 0, HID_KEY_BACKSLASH},
    {']', 0, HID_KEY_BRACKET_RIGHT},
    {'^', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_6},
    {'_', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_MINUS},
    {'`', 0, HID_KEY_GRAVE},
    {'{', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_BRACKET_LEFT},
    {'|', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_BACKSLASH},
    {'}', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_BRACKET_RIGHT},
    {'~', KEYBOARD_MODIFIER_LEFTSHIFT, HID_KEY_GRAVE}
};