[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
lib_deps =
  bodmer/TFT_eSPI
  fbiego/CST816S
  rweather/Crypto
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_MODE=1
  -DTFT_eSPI_SPRITE_PSRAM